- name: Install golang
  ansible.builtin.yum:
    name:
      - golang

  state: installed

- name: Include app_prerequisites
  ansible.builtin.import_tasks:
    file: app_prereq.yml

- name: Install Golang Dependencies
  ansible.builtin.shell:  go mod init dispatch ; go get ; go build
  args:
   chdir: /app

- name: Include schema setup
  ansible.builtin.import_tasks:
    file: schema_setup.yml

- name: Include SystemD
  ansible.builtin.import_tasks:
    file: systemd_setup.yml





